name: WallStreetv2
version: '1.0-SNAPSHOT'
main: wrenthen.wallStreetv2.WallStreetv2
api-version: '1.21'
depend: [WorldEdit]
commands:
  c:
    description: Manages Company
  wsa:
    description: Wall Street Admin setup
